jenkins:
  clouds:
    - amazonEC2:
        cloudName: "build-agents"
        instanceCapStr: "100"
        noDelayProvisioning: true
        sshKeysCredentialsId: "jenkins-ec2-agent-ssh-key"
        region: "ap-southeast-2"
        useInstanceProfileForCredentials: false
        templates:
          - ami: "${jenkins-build-agent-ami-id}"
            amiType:
              unixData:
                slaveCommandPrefix: "sudo"
                sshPort: "22"
            associatePublicIp: false
            zone: "${jenkins-az}"
            connectionStrategy: "PRIVATE_IP"
            customDeviceMapping: "/dev/xvda=:100"
            connectBySSHProcess: false
            deleteRootOnTermination: false
            description: "default-agent-build"
            ebsOptimized: false
            hostKeyVerificationStrategy: ACCEPT_NEW
            idleTerminationMinutes: "240"
            iamInstanceProfile: ${jenkins-iam-role-arn}
            initScript: "sudo yum update -y\nsudo yum update -y --security\nsudo yum install git docker jq -y\nsudo amazon-linux-extras\
              \ enable corretto8\nsudo amazon-linux-extras install corretto8 -y\nEC2_INSTANCE_ID=$(ec2-metadata\
              \ --instance-id)\nwget ${jenkins-domain-url}/jnlpJars/agent.jar\
              \ -O agent.jar\njava -jar agent.jar -jnlpUrl ${jenkins-domain-url}/computer/$EC2_INSTANCE_ID\
              \ slave-agent.jnlp\nsudo usermod -a -G docker ec2-user\nsudo service docker start\nsudo systemctl\
              \ enable docker\necho Pulling SSM parameters and Jenkins image...\n\
              \ export ArtifactoryUser=$(aws --region=ap-southeast-2 ssm get-parameter --name \"/Jenkins/ArtifactoryUser\" --with-decryption --output text --query Parameter.Value)\n\
              \ export ArtifactoryPassword=$(aws --region=ap-southeast-2 ssm get-parameter --name \"/Jenkins/ArtifactoryPassword\" --with-decryption --output text --query Parameter.Value)\n\
              \ sudo docker login url.com --username \"$ArtifactoryUser\" --password \"$ArtifactoryPassword\""
            instanceCapStr: "1"
            labelString: "squad-build"
            mode: EXCLUSIVE
            monitoring: false
            numExecutors: 10
            remoteAdmin: "ec2-user"
            remoteFS: ""
            securityGroups: "${jenkins-ec2-agents-security-group}"
            subnetId: "${jenkins-subnet}"
            stopOnTerminate: false
            tags:
              - name: "Name"
                value: "Dynamic Jenkins Agent"
            type: M5Large
            useDedicatedTenancy: false
            useEphemeralDevices: false
    - ecs:
        credentialsId: ""
        cluster: "${jenkins-agents-cluster-arn}"
        jenkinsUrl: "${jenkins-domain-url}/"
        name: "ecs-cloud"
        regionName: "ap-southeast-2"
        allowedOverrides: "label,image,inheritFrom"
        templates:
          - assignPublicIp: false
            cpu: 4096
            environments:
              - name: "JENKINS_WEB_SOCKET"
                value: "true"
            executionRole:  "${enablement-task-execution-role}"
            image: "1111111111111111.dkr.ecr.ap-southeast-2.amazonaws.com/worker:latest"
            repositoryCredentials: ""
            label: "base-worker"
            launchType: "FARGATE"
            logDriver: "awslogs"
            logDriverOptions:
              - name: "awslogs-group"
                value: "${jenkins-log-group-name}"
              - name: "awslogs-region"
                value: "ap-southeast-2"
              - name: "awslogs-stream-prefix"
                value: "ecs-jenkins-agents"
            memory: 0
            memoryReservation: 16384
            networkMode: "awsvpc"
            platformVersion: "1.4.0"
            privileged: false
            remoteFSRoot: "/home/jenkins"
            securityGroups: "${jenkins-ec2-agents-security-group}"
            sharedMemorySize: 0
            subnets: "${jenkins-subnets}"
            taskrole: "${enablement-task-execution-role}"
            templateName: "jenkins-agent-test-task"
            uniqueRemoteFSRoot: false
